version: "3.9"  # optional since v1.27.0
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'MealManager'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
  web:
    build: .
    image: mealmanager
    environment:
      DB_HOST: db
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  my-db: